version: "3.01"

services:
  api-db:
    image: mysql:${MYSQL_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
        - db-data:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306

networks:
  backend:

volumes:
  db-data: