# This Action for yarn enables arbitrary actions with the yarn command-line client, including testing packages
# For more information see: https://github.com/marketplace/actions/github-action-for-yarn

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
    # - uses: borales/actions-yarn@v2.0.0
    #   with:
    #     cmd: test # will run `yarn test` command
    - name: Test
      run: docker-compose up --exit-code-from api
